from angular_states import plot_angular_states
from linear_states import plot_linear_states
from foot_positions import plot_feet_positions
from foot_velocities import plot_feet_velocity
from joint_angles import plot_joint_angles
from joint_velocities import plot_joint_velocities
from joint_effort import plot_joint_effort
from body_and_foot_trajs import plot_body_and_foot_trajectories

mcap_file = "bag_file/robot_1_quad_log_spirit_20251008_1525_0.mcap"

plot_feet_positions(mcap_file)
plot_feet_velocity(mcap_file)
plot_joint_effort(mcap_file)
plot_joint_velocities(mcap_file)
plot_linear_states(mcap_file)
plot_angular_states(mcap_file)
plot_joint_angles(mcap_file)
plot_body_and_foot_trajectories(mcap_file)

